version: '3'
services:
  phx:
    image: alvarolizama/phoenix:1.3-base
    ports:
      - ${PHX_HOST_PORT}:${PHX_PORT}
    volumes:
      - ./src:/app/src
      - ./scripts:/scripts
      - ./src/_build/prod/rel:/app/src/_build/prod/rel
      - phx.deps:/app/src/deps
      - phx.builds:/app/src/_build
      - phx.nodejs:/app/src/assets/node_modules
    depends_on:
      - postgres
    environment:
      - MIX_ENV=${ENV}
      - PHX_PORT=${PHX_PORT}
      - PHX_URL_HOST=${PHX_URL_HOST}
      - PHX_SECRET_KEY_BASE=${PHX_SECRET_KEY_BASE}
      - PG_DATABASE_URL=ecto://postgres:postgres@postgres/${PG_DATABASE_NAME}_${ENV}
    working_dir: /app/src
    command: mix phx.server

  postgres:
    image: postgres

volumes:
  phx.deps:
  phx.builds:
  phx.nodejs:
